#!/usr/bin/env python3
"""Generate a self-contained HTML report for one agent task — HOST-SIDE oversight.

Runs outside the jail (same side as a forge push), automatically after an agent
task. It combines the agent's own written explanation (`.ragent/EXPLAIN.md`, which
AGENTS.md asks the agent to leave) with the real git diff of its branch, and
renders a self-contained, offline HTML page so a human can review the *reasoning*
and the *change* together — a universal oversight channel that needs no forge.

Reuses the OKF renderer (tools/okf_render.py) for the prose; renders the diff with
its own neon add/del colouring. Serve the output with tools/ragent-serve.sh.

Usage:  ragent-report.py <clone-dir> <task> [base-ref]
"""

import sys
import os
import re
import html
import subprocess
import datetime

# Reuse the OKF renderer that sits next to this script (same store dir / tools dir).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import okf_render  # noqa: E402  (md_to_html + CSS; its main() is __main__-guarded)


def git(clone, *args):
    return subprocess.run(["git", "-C", clone, *args],
                          capture_output=True, text=True).stdout


def colorize_diff(diff_text):
    """Render a unified diff as HTML with neon add/del colouring (no green)."""
    out = []
    for line in diff_text.splitlines():
        esc = html.escape(line)
        if line.startswith("+++") or line.startswith("---"):
            cls = "d-file"
        elif line.startswith("@@"):
            cls = "d-hunk"
        elif line.startswith("+"):
            cls = "d-add"
        elif line.startswith("-"):
            cls = "d-del"
        else:
            cls = "d-ctx"
        out.append(f'<span class="{cls}">{esc or "&nbsp;"}</span>')
    return '<pre class="diff">' + "\n".join(out) + "</pre>"


REPORT_CSS = """
.report-meta{background:var(--card);border:1px solid var(--border);border-radius:8px;
padding:.5rem .9rem;margin:1rem 0 1.5rem;font-size:.9rem}
.report-meta .k{color:var(--muted);display:inline-block;min-width:7em}
pre.diff{background:#16181d;color:#c8d3f5;padding:1rem;border-radius:8px;overflow-x:auto;
border:1px solid var(--border);font:.82rem/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
pre.diff span{display:block;white-space:pre}
.d-add{color:#86e1fc}          /* neon cyan = addition (no green) */
.d-del{color:#ff757f}          /* neon red  = deletion */
.d-hunk{color:#c099ff}         /* purple    = hunk header */
.d-file{color:#ffc777;font-weight:600}
.d-ctx{color:#828bb8}
.status{display:inline-block;font-size:.72rem;font-weight:700;text-transform:uppercase;
letter-spacing:.04em;color:#1a1b26;background:#ffc777;padding:.15em .6em;border-radius:20px}
.status.resolved{background:#86e1fc}
"""


def report_page(title, body):
    return "\n".join([
        "<!doctype html><html lang=en><head><meta charset=utf-8>",
        '<meta name=viewport content="width=device-width,initial-scale=1">',
        "<title>%s</title>" % html.escape(title),
        "<style>%s\n%s</style></head><body>" % (okf_render.CSS, REPORT_CSS),
        "<!-- GENERATED by tools/ragent-report.py — do not edit. -->",
        '<div class="wrap">',
        '<div class="nav"><a href="index.html">← all task reports</a></div>',
        body,
        '<div class="footer">Generated by <code>tools/ragent-report.py</code> — the '
        "agent's explanation + the real diff of its branch. Review, then accept or "
        "request changes on the primary device.</div>",
        "</div></body></html>",
    ])


def read_explanation(clone):
    """Prefer the agent's deliberate EXPLAIN.md; fall back to a stripped log tail."""
    p = os.path.join(clone, ".ragent", "EXPLAIN.md")
    if os.path.exists(p) and os.path.getsize(p) > 0:
        return okf_render.md_to_html(open(p, encoding="utf-8").read().strip()), True
    log = os.path.join(clone, ".ragent", "agent.log")
    if os.path.exists(log):
        raw = open(log, encoding="utf-8", errors="replace").read()
        clean = re.sub(r"\x1b\[[0-9;?]*[A-Za-z]", "", raw)
        tail = "\n".join([l for l in clean.splitlines() if l.strip()][-40:])
        return ("<p><em>No <code>.ragent/EXPLAIN.md</code> was left by the agent — "
                "showing its last output instead.</em></p><pre>%s</pre>"
                % html.escape(tail)), False
    return "<p><em>No explanation and no log found.</em></p>", False


def main():
    if len(sys.argv) < 3:
        print("usage: ragent-report.py <clone-dir> <task> [base-ref]", file=sys.stderr)
        return 2
    clone = os.path.abspath(sys.argv[1])
    task = sys.argv[2]
    branch = "agent/%s" % task
    base = sys.argv[3] if len(sys.argv) > 3 else \
        (git(clone, "rev-parse", "--verify", "-q", "origin/HEAD").strip() or "HEAD~1")

    reports = os.path.join(clone, ".ragent", "reports")
    htmldir = os.path.join(reports, "html")
    os.makedirs(htmldir, exist_ok=True)

    explanation_html, had_explain = read_explanation(clone)
    diff = git(clone, "diff", "%s..%s" % (base, branch)) or git(clone, "diff", base)
    stat = git(clone, "diff", "--stat", "%s..%s" % (base, branch)) or "(no diff)"
    commits = git(clone, "log", "--oneline", "%s..%s" % (base, branch)).strip()
    ts = datetime.datetime.now().isoformat(timespec="seconds")

    body = "\n".join([
        "<h1>Task report — %s</h1>" % html.escape(task),
        '<div class="report-meta">'
        '<div><span class="k">task</span>%s</div>'
        '<div><span class="k">branch</span><code>%s</code> vs base <code>%s</code></div>'
        '<div><span class="k">commits</span>%s</div>'
        '<div><span class="k">generated</span>%s</div>'
        '<div><span class="k">explanation</span>%s</div></div>' % (
            html.escape(task), html.escape(branch), html.escape(base),
            html.escape(commits.replace("\n", " · ") or "—"), ts,
            "agent-written (EXPLAIN.md)" if had_explain else "log fallback"),
        "<h2>What the agent did</h2>", explanation_html,
        "<h2>Changed files</h2>", "<pre>%s</pre>" % html.escape(stat.strip()),
        "<h2>Diff</h2>", colorize_diff(diff.strip() or "(empty)"),
    ])
    open(os.path.join(htmldir, "%s.html" % task), "w", encoding="utf-8").write(
        report_page("Task report — %s" % task, body))
    write_index(htmldir)
    print(os.path.join(htmldir, "%s.html" % task))
    return 0


def write_index(htmldir):
    rows = []
    for f in sorted(os.listdir(htmldir)):
        if f.endswith(".html") and f != "index.html":
            name = f[:-5]
            rows.append('<div class="card"><div class="t"><a href="%s">%s</a></div></div>'
                        % (html.escape(f), html.escape(name)))
    body = ("<h1>Task reports</h1><p class=\"gen\">The agent's explanation + the real "
            "diff for each task. Newest tasks appear as you run them.</p>"
            '<div class="cards">%s</div>' % ("".join(rows) or "<p>No reports yet.</p>"))
    open(os.path.join(htmldir, "index.html"), "w", encoding="utf-8").write(
        report_page("Task reports", body))


if __name__ == "__main__":
    sys.exit(main())
